import { LevelConfig } from '../types';

export const GAME_LEVELS: LevelConfig[] = [
  {
    id: 1,
    titleHi: "शाही मोर (Royal Peacock)",
    titleEn: "Royal Peacock",
    categoryHi: "पक्षी एवं वन्यजीव",
    categoryEn: "Wildlife & Birds",
    gridSize: 2,
    hasRotation: false,
    difficultyHi: "सरल (2x2 ग्रिड - 4 टुकड़े)",
    difficultyEn: "Easy (2x2 Grid - 4 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 2,
    titleHi: "रॉयल बंगाल टाइगर (Bengal Tiger)",
    titleEn: "Royal Bengal Tiger",
    categoryHi: "वन्यजीव",
    categoryEn: "Wildlife",
    gridSize: 2,
    hasRotation: false,
    difficultyHi: "सरल (2x2 ग्रिड - 4 टुकड़े)",
    difficultyEn: "Easy (2x2 Grid - 4 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 3,
    titleHi: "एशियाई हाथी (Asian Elephant)",
    titleEn: "Asian Elephant",
    categoryHi: "वन्यजीव",
    categoryEn: "Wildlife",
    gridSize: 2,
    hasRotation: false,
    difficultyHi: "सरल (2x2 ग्रिड - 4 टुकड़े)",
    difficultyEn: "Easy (2x2 Grid - 4 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 4,
    titleHi: "कस्तूरी मृग (Spotted Deer)",
    titleEn: "Spotted Forest Deer",
    categoryHi: "वन्यजीव",
    categoryEn: "Wildlife",
    gridSize: 2,
    hasRotation: false,
    difficultyHi: "सरल (2x2 ग्रिड - 4 टुकड़े)",
    difficultyEn: "Easy (2x2 Grid - 4 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1484406566174-9da000fda645?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 5,
    titleHi: "सुनहरा गरुड़ (Golden Eagle)",
    titleEn: "Golden Eagle",
    categoryHi: "पक्षी जगत",
    categoryEn: "Birds of Prey",
    gridSize: 2,
    hasRotation: false,
    difficultyHi: "सरल (2x2 ग्रिड - 4 टुकड़े)",
    difficultyEn: "Easy (2x2 Grid - 4 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 6,
    titleHi: "भारतीय किंगफिशर (Kingfisher)",
    titleEn: "Indian Kingfisher",
    categoryHi: "पक्षी जगत",
    categoryEn: "Birds",
    gridSize: 2,
    hasRotation: true,
    difficultyHi: "सरल + रोटेशन (2x2 + ↺)",
    difficultyEn: "Easy + Rotated (2x2 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1555169062-013468b47731?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 7,
    titleHi: "बर्फीला तेंदुआ (Snow Leopard)",
    titleEn: "Snow Leopard",
    categoryHi: "वन्यजीव",
    categoryEn: "Wildlife",
    gridSize: 2,
    hasRotation: true,
    difficultyHi: "सरल + रोटेशन (2x2 + ↺)",
    difficultyEn: "Easy + Rotated (2x2 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1574063413132-355dbfd83e25?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 8,
    titleHi: "गुलाबी राजहंस (Pink Flamingos)",
    titleEn: "Pink Flamingos",
    categoryHi: "पक्षी जगत",
    categoryEn: "Birds",
    gridSize: 2,
    hasRotation: true,
    difficultyHi: "सरल + रोटेशन (2x2 + ↺)",
    difficultyEn: "Easy + Rotated (2x2 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9,
    titleHi: "लाल पांडा (Red Panda)",
    titleEn: "Cute Red Panda",
    categoryHi: "वन्यजीव",
    categoryEn: "Wildlife",
    gridSize: 2,
    hasRotation: true,
    difficultyHi: "सरल + रोटेशन (2x2 + ↺)",
    difficultyEn: "Easy + Rotated (2x2 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 10,
    titleHi: "शेर बब्बर (Asiatic Lion)",
    titleEn: "Majestic Asiatic Lion",
    categoryHi: "वन्यजीव",
    categoryEn: "Wildlife",
    gridSize: 2,
    hasRotation: true,
    difficultyHi: "सरल + रोटेशन (2x2 + ↺)",
    difficultyEn: "Easy + Rotated (2x2 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 11,
    titleHi: "भव्य ताजमहल (Taj Mahal)",
    titleEn: "Majestic Taj Mahal",
    categoryHi: "धरोहर एवं वास्तुकला",
    categoryEn: "Heritage & Architecture",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 12,
    titleHi: "स्वर्ण मंदिर (Golden Temple)",
    titleEn: "Golden Temple, Amritsar",
    categoryHi: "धरोहर",
    categoryEn: "Heritage",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 13,
    titleHi: "हवा महल जयपुर (Hawa Mahal)",
    titleEn: "Hawa Mahal Palace, Jaipur",
    categoryHi: "धरोहर",
    categoryEn: "Heritage",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 14,
    titleHi: "लाल किला दिल्ली (Red Fort)",
    titleEn: "Red Fort, Delhi",
    categoryHi: "ऐतिहासिक स्मारक",
    categoryEn: "Monuments",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 15,
    titleHi: "कुतुब मीनार (Qutub Minar)",
    titleEn: "Qutub Minar, Delhi",
    categoryHi: "ऐतिहासिक स्मारक",
    categoryEn: "Monuments",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1600100397608-f010f4439c2c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 16,
    titleHi: "गेटवे ऑफ इंडिया (Gateway of India)",
    titleEn: "Gateway of India, Mumbai",
    categoryHi: "धरोहर",
    categoryEn: "Heritage",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 17,
    titleHi: "काशी विश्वनाथ गंगा घाट (Varanasi Ghats)",
    titleEn: "Ganga Ghats, Varanasi",
    categoryHi: "धरोहर एवं संस्कृति",
    categoryEn: "Spiritual Heritage",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 18,
    titleHi: "मैसूर राजमहल (Mysore Palace)",
    titleEn: "Royal Mysore Palace",
    categoryHi: "राजमहल",
    categoryEn: "Palaces",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1566552881560-0be86c532298?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 19,
    titleHi: "कोणार्क सूर्य मंदिर (Konark Sun Temple)",
    titleEn: "Konark Sun Temple, Odisha",
    categoryHi: "धरोहर",
    categoryEn: "Heritage",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1624726175512-19b9baf9fbd1?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 20,
    titleHi: "मीनाक्षी अम्मन मंदिर (Meenakshi Temple)",
    titleEn: "Meenakshi Amman Temple, Madurai",
    categoryHi: "धरोहर",
    categoryEn: "Heritage",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 21,
    titleHi: "जैसलमेर स्वर्ण किला (Jaisalmer Golden Fort)",
    titleEn: "Jaisalmer Desert Fort",
    categoryHi: "किले व धरोहर",
    categoryEn: "Forts & Castles",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 22,
    titleHi: "चारमीनार हैदराबाद (Charminar)",
    titleEn: "Charminar, Hyderabad",
    categoryHi: "धरोहर",
    categoryEn: "Heritage",
    gridSize: 3,
    hasRotation: false,
    difficultyHi: "मध्यम (3x3 ग्रिड - 9 टुकड़े)",
    difficultyEn: "Medium (3x3 Grid - 9 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 23,
    titleHi: "एफिल टॉवर पेरिस (Eiffel Tower)",
    titleEn: "Eiffel Tower, Paris",
    categoryHi: "विश्व अजूबे",
    categoryEn: "World Wonders",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 24,
    titleHi: "कोलोसियम रोम (Colosseum)",
    titleEn: "Colosseum, Rome",
    categoryHi: "विश्व अजूबे",
    categoryEn: "World Wonders",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 25,
    titleHi: "चीन की विशाल दीवार (Great Wall of China)",
    titleEn: "Great Wall of China",
    categoryHi: "विश्व अजूबे",
    categoryEn: "World Wonders",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 26,
    titleHi: "बिग बेन लंदन (Big Ben London)",
    titleEn: "Big Ben Clock Tower, London",
    categoryHi: "विश्व धरोहर",
    categoryEn: "World Landmarks",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1581010864468-c972b8705439?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 27,
    titleHi: "सिडनी ओपेरा हाउस (Sydney Opera House)",
    titleEn: "Sydney Opera House",
    categoryHi: "विश्व वास्तुकला",
    categoryEn: "World Architecture",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 28,
    titleHi: "माचू पिच्चू पेरू (Machu Picchu)",
    titleEn: "Inca Citadel, Machu Picchu",
    categoryHi: "विश्व अजूबे",
    categoryEn: "World Wonders",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 29,
    titleHi: "गीज़ा के पिरामिड (Pyramids of Giza)",
    titleEn: "Pyramids of Giza, Egypt",
    categoryHi: "विश्व अजूबे",
    categoryEn: "World Wonders",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 30,
    titleHi: "वेनिस की नहरें (Venice Grand Canal)",
    titleEn: "Grand Canal, Venice Italy",
    categoryHi: "विश्व धरोहर",
    categoryEn: "World Landmarks",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 31,
    titleHi: "पेट्रा खजाना जॉर्डन (Treasury of Petra)",
    titleEn: "The Treasury, Petra Jordan",
    categoryHi: "विश्व अजूबे",
    categoryEn: "World Wonders",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1548247416-ec66f4900b2e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 32,
    titleHi: "क्राइस्ट द रिडीमर (Christ the Redeemer)",
    titleEn: "Christ the Redeemer, Rio",
    categoryHi: "विश्व धरोहर",
    categoryEn: "World Landmarks",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 33,
    titleHi: "बुर्ज खलीफा दुबई (Burj Khalifa Dubai)",
    titleEn: "Burj Khalifa Skycraper, Dubai",
    categoryHi: "आधुनिक वास्तुकला",
    categoryEn: "Modern Architecture",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 34,
    titleHi: "टोक्यो नियॉन सिटी (Tokyo Neon Nights)",
    titleEn: "Tokyo Shinjuku Neon City",
    categoryHi: "आधुनिक शहर",
    categoryEn: "Modern Cities",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 35,
    titleHi: "सांतोरिनी ग्रीस (Santorini Blue Domes)",
    titleEn: "Santorini Island, Greece",
    categoryHi: "विश्व सौंदर्य",
    categoryEn: "Scenic Landscapes",
    gridSize: 3,
    hasRotation: true,
    difficultyHi: "मध्यम + रोटेशन (3x3 + ↺)",
    difficultyEn: "Medium + Rotated (3x3 + ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 36,
    titleHi: "हिमालय हिमशिखर (Himalayan Peaks)",
    titleEn: "Himalayan Snow Peaks",
    categoryHi: "प्रकृति एवं पर्वत",
    categoryEn: "Nature & Mountains",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 37,
    titleHi: "योसेमाइट झरना (Yosemite Falls)",
    titleEn: "Yosemite Grand Waterfall",
    categoryHi: "प्रकृति एवं जलप्रपात",
    categoryEn: "Nature & Waterfalls",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 38,
    titleHi: "अमेज़न वर्षावन (Amazon Rainforest)",
    titleEn: "Amazon Rainforest Canopy",
    categoryHi: "प्रकृति व वन",
    categoryEn: "Nature & Forests",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 39,
    titleHi: "नॉर्दर्न लाइट्स ऑरोरा (Aurora Borealis)",
    titleEn: "Northern Lights Aurora Borealis",
    categoryHi: "प्राकृतिक चमत्कार",
    categoryEn: "Natural Wonders",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1498887960847-2a5e46312788?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 40,
    titleHi: "ग्रांड कैन्यन (Grand Canyon Arizona)",
    titleEn: "Grand Canyon Red Rocks",
    categoryHi: "प्राकृतिक चमत्कार",
    categoryEn: "Natural Wonders",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 41,
    titleHi: "माउंट फूजी सूर्यास्त (Mount Fuji Sunset)",
    titleEn: "Mount Fuji Sunset, Japan",
    categoryHi: "पर्वत एवं सूर्यास्त",
    categoryEn: "Mountains & Sunset",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 42,
    titleHi: "सहारा मरुस्थल (Sahara Sand Dunes)",
    titleEn: "Sahara Golden Sand Dunes",
    categoryHi: "रेगिस्तान",
    categoryEn: "Deserts",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 43,
    titleHi: "मालदीव लैगून (Maldives Lagoon)",
    titleEn: "Maldives Crystal Clear Lagoon",
    categoryHi: "समुद्री तट",
    categoryEn: "Beaches & Oceans",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 44,
    titleHi: "विक्टोरिया जलप्रपात (Victoria Falls)",
    titleEn: "Victoria Falls Mist",
    categoryHi: "जलप्रपात",
    categoryEn: "Waterfalls",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 45,
    titleHi: "स्विस आल्प्स घाटी (Swiss Alps Valley)",
    titleEn: "Swiss Alps Mountain Meadow",
    categoryHi: "पर्वत एवं वादियां",
    categoryEn: "Valleys & Mountains",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 46,
    titleHi: "बांफ लेक लुईस (Banff Lake Louise)",
    titleEn: "Lake Louise Turquoise Waters, Canada",
    categoryHi: "झील एवं पर्वत",
    categoryEn: "Lakes & Peaks",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 47,
    titleHi: "क्योटो बांस वन (Kyoto Bamboo Grove)",
    titleEn: "Arashiyama Bamboo Grove, Kyoto",
    categoryHi: "प्रकृति व वन",
    categoryEn: "Forests",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 48,
    titleHi: "आइसलैंड विस्मयकारी झरना (Iceland Waterfall)",
    titleEn: "Iceland Glacial Waterfall",
    categoryHi: "जलप्रपात",
    categoryEn: "Waterfalls",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 49,
    titleHi: "चेरी ब्लॉसम बहार (Cherry Blossoms)",
    titleEn: "Spring Cherry Blossom Trees",
    categoryHi: "पुष्प एवं उद्यान",
    categoryEn: "Floral & Gardens",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 50,
    titleHi: "हॉलैंड ट्यूलिप खेत (Dutch Tulip Fields)",
    titleEn: "Rainbow Tulip Farm, Netherlands",
    categoryHi: "पुष्प एवं उद्यान",
    categoryEn: "Floral & Gardens",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 51,
    titleHi: "सुनहरी सूरजमुखी वाटिका (Golden Sunflowers)",
    titleEn: "Summer Sunflower Blossom Valley",
    categoryHi: "पुष्प एवं प्रकृति",
    categoryEn: "Floral & Nature",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 52,
    titleHi: "शरद ऋतु स्वर्णिम वन (Golden Autumn Forest)",
    titleEn: "Golden Autumn Maple Forest",
    categoryHi: "प्रकृति व वन",
    categoryEn: "Nature & Seasons",
    gridSize: 4,
    hasRotation: false,
    difficultyHi: "कठिन (4x4 ग्रिड - 16 टुकड़े)",
    difficultyEn: "Challenging (4x4 Grid - 16 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 53,
    titleHi: "लाल रंग की फेरारी (Red Ferrari Supercar)",
    titleEn: "Red Ferrari Sports Car",
    categoryHi: "ऑटोमोबाइल",
    categoryEn: "Automobile",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 54,
    titleHi: "लेम्बोर्गिनी एवेंटाडोर (Lamborghini Aventador)",
    titleEn: "Yellow Lamborghini Aventador",
    categoryHi: "सुपरकार्स",
    categoryEn: "Supercars",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 55,
    titleHi: "पोर्श 911 टर्बो (Porsche 911 Turbo)",
    titleEn: "Sleek Porsche 911 Carrera",
    categoryHi: "सुपरकार्स",
    categoryEn: "Supercars",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 56,
    titleHi: "क्लासिक फोर्ड मस्टैंग (Classic Mustang)",
    titleEn: "1969 Classic Ford Mustang Mach 1",
    categoryHi: "क्लासिक विंटेज कारें",
    categoryEn: "Classic Vintage Cars",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 57,
    titleHi: "शेवरले कोर्वेट (Chevrolet Corvette)",
    titleEn: "Chevrolet Corvette Stingray Racing",
    categoryHi: "सुपरकार्स",
    categoryEn: "Supercars",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 58,
    titleHi: "बीएमडब्ल्यू एम8 कॉम्पिटिशन (BMW M8)",
    titleEn: "BMW M8 Competition Coupe",
    categoryHi: "लक्जरी स्पोर्ट्स कारें",
    categoryEn: "Luxury Sports Cars",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 59,
    titleHi: "ऑडी आर8 वी10 (Audi R8 V10)",
    titleEn: "Audi R8 V10 Performance",
    categoryHi: "सुपरकार्स",
    categoryEn: "Supercars",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 60,
    titleHi: "फॉर्मूला 1 रेस कार (Formula 1 Race Car)",
    titleEn: "Formula 1 High-Speed Track Racer",
    categoryHi: "मोटर स्पोर्ट्स",
    categoryEn: "Motorsports",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 61,
    titleHi: "ग्रेट बैरियर रीफ कोरल (Coral Reef)",
    titleEn: "Vibrant Great Barrier Reef Coral",
    categoryHi: "समुद्री जीवन",
    categoryEn: "Marine Life",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 62,
    titleHi: "समुद्री कछुआ (Sea Turtle Glider)",
    titleEn: "Green Sea Turtle Ocean Flight",
    categoryHi: "समुद्री जीवन",
    categoryEn: "Marine Life",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 63,
    titleHi: "नीली डॉल्फिन छलांग (Blue Dolphin Leap)",
    titleEn: "Pacific Ocean Bottlenose Dolphin",
    categoryHi: "समुद्री जीवन",
    categoryEn: "Marine Life",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 64,
    titleHi: "क्लाउनफिश और एनीमोन (Clownfish Habitat)",
    titleEn: "Orange Clownfish in Sea Anemone",
    categoryHi: "समुद्री जीवन",
    categoryEn: "Marine Life",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 65,
    titleHi: "विशाल ब्लू व्हेल (Giant Blue Whale)",
    titleEn: "Majestic Ocean Blue Whale",
    categoryHi: "समुद्री दिग्गज",
    categoryEn: "Deep Ocean Life",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1520637736862-23c2a05f3299?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 66,
    titleHi: "दीप्तिमान जेलीफ़िश (Luminescent Jellyfish)",
    titleEn: "Deep Sea Bioluminescent Jellyfish",
    categoryHi: "समुद्री चमत्कार",
    categoryEn: "Deep Ocean Wonders",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 67,
    titleHi: "मंटा रे विशाल पंख (Giant Manta Ray)",
    titleEn: "Ocean Manta Ray Gliding",
    categoryHi: "समुद्री जीवन",
    categoryEn: "Marine Life",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 68,
    titleHi: "बर्फीला ध्रुवीय भालू (Arctic Polar Bear)",
    titleEn: "Arctic Polar Bear on Ice",
    categoryHi: "ध्रुवीय वन्यजीव",
    categoryEn: "Arctic Wildlife",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 69,
    titleHi: "अफ्रीकी सवाना जिराफ (African Savanna Giraffe)",
    titleEn: "Sunset Savanna Giraffes, Kenya",
    categoryHi: "वन्यजीव",
    categoryEn: "Wildlife",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1535083783855-76ae62b2914e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 70,
    titleHi: "रेड फॉक्स लोमड़ी (Forest Red Fox)",
    titleEn: "Winter Snow Red Fox",
    categoryHi: "वन्यजीव",
    categoryEn: "Wildlife",
    gridSize: 4,
    hasRotation: true,
    difficultyHi: "अति कठिन (4x4 + उल्टे टुकड़े ↺)",
    difficultyEn: "Very Hard (4x4 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1548247416-ec66f4900b2e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 71,
    titleHi: "कॉस्मिक नेबुला (Cosmic Orion Nebula)",
    titleEn: "Cosmic Orion Nebula Galaxy",
    categoryHi: "अंतरिक्ष व खगोल",
    categoryEn: "Space & Astronomy",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 72,
    titleHi: "अंतरिक्ष से पृथ्वी दर्शन (Earth from Orbit)",
    titleEn: "Blue Planet Earth from Satellite Orbit",
    categoryHi: "अंतरिक्ष व खगोल",
    categoryEn: "Space & Astronomy",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 73,
    titleHi: "शनि ग्रह के स्वर्णिम वलय (Saturn Rings)",
    titleEn: "Saturn Rings and Solar Orbit",
    categoryHi: "सौरमंडल",
    categoryEn: "Solar System",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 74,
    titleHi: "मंगल ग्रह रोवर घाटी (Mars Exploration)",
    titleEn: "Mars Red Planet Landscape Exploration",
    categoryHi: "सौरमंडल",
    categoryEn: "Solar System",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 75,
    titleHi: "मिल्की वे आकाशगंगा (Milky Way Galactic Core)",
    titleEn: "Milky Way Core Over Night Mountains",
    categoryHi: "अंतरिक्ष व खगोल",
    categoryEn: "Space & Astronomy",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 76,
    titleHi: "जेम्स वेब डीप स्पेस (James Webb Deep Cosmos)",
    titleEn: "Deep Universe Galaxies and Cosmic Clusters",
    categoryHi: "गहन ब्रह्मांड",
    categoryEn: "Deep Cosmos",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1484589065579-248aad0d8b13?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 77,
    titleHi: "स्पेस शटल प्रक्षेपण (Space Shuttle Launch)",
    titleEn: "Rocket Lift-Off into Outer Space",
    categoryHi: "अंतरिक्ष विज्ञान",
    categoryEn: "Space Missions",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 78,
    titleHi: "सुपरनोवा तारा विस्फोट (Supernova Cosmic Blast)",
    titleEn: "Stellar Supernova Explosion in Space",
    categoryHi: "गहन ब्रह्मांड",
    categoryEn: "Deep Cosmos",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 79,
    titleHi: "एंड्रोमेडा गैलेक्सी (Andromeda Spiral Galaxy)",
    titleEn: "Andromeda Spiral Galactic Arms",
    categoryHi: "गहन ब्रह्मांड",
    categoryEn: "Deep Cosmos",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 80,
    titleHi: "अंतर्राष्ट्रीय अंतरिक्ष स्टेशन (ISS in Orbit)",
    titleEn: "International Space Station Above Earth",
    categoryHi: "अंतरिक्ष विज्ञान",
    categoryEn: "Space Missions",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 81,
    titleHi: "चंद्रमा क्रेटर एवं लैंडर (Moon Crater Landing)",
    titleEn: "Lunar Surface High Definition Detail",
    categoryHi: "सौरमंडल",
    categoryEn: "Solar System",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 82,
    titleHi: "सौर तूफानी ज्वाला (Solar Flare Blast)",
    titleEn: "Solar Corona Prominence Flare",
    categoryHi: "सौर विज्ञान",
    categoryEn: "Solar Wonders",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 83,
    titleHi: "रहस्यमयी पल्सर तारा (Pulsar Star Waves)",
    titleEn: "Neutron Pulsar Magnetic Energy Waves",
    categoryHi: "गहन ब्रह्मांड",
    categoryEn: "Deep Cosmos",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1484589065579-248aad0d8b13?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 84,
    titleHi: "ब्लैक होल घटना क्षितिज (Black Hole Singularity)",
    titleEn: "Supermassive Black Hole Accretion Disk",
    categoryHi: "गहन ब्रह्मांड",
    categoryEn: "Deep Cosmos",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 85,
    titleHi: "हबल डीप स्टार क्लस्टर (Hubble Star Cluster)",
    titleEn: "Globular Star Cluster Millions of Stars",
    categoryHi: "गहन ब्रह्मांड",
    categoryEn: "Deep Cosmos",
    gridSize: 5,
    hasRotation: false,
    difficultyHi: "मास्टर लेवल (5x5 ग्रिड - 25 टुकड़े)",
    difficultyEn: "Master Level (5x5 Grid - 25 Pieces)",
    imageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 86,
    titleHi: "साइबरपंक 2099 शहर (Cyberpunk Mega City 2099)",
    titleEn: "Cyberpunk Metropolis Neon Holograms",
    categoryHi: "साइ-फाई व भविष्य",
    categoryEn: "Sci-Fi & Cyberpunk",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 87,
    titleHi: "भविष्यवादी होवर कार (Futuristic Hover Speedster)",
    titleEn: "Futuristic Anti-Gravity Hover Racer",
    categoryHi: "साइ-फाई व भविष्य",
    categoryEn: "Sci-Fi & Vehicles",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 88,
    titleHi: "नीयन मैट्रिक्स चक्र (Neon Cyber Matrix)",
    titleEn: "Quantum Matrix Neon Cybernetic Grid",
    categoryHi: "साइ-फाई व कला",
    categoryEn: "Digital Art & Sci-Fi",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 89,
    titleHi: "3D बहुरंगी क्रिस्टल प्रिज्म (Prismatic Crystal)",
    titleEn: "Prismatic Light Refraction Geometry",
    categoryHi: "अमूर्त कला",
    categoryEn: "Abstract Geometrics",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 90,
    titleHi: "क्वांटम फ्यूजन कोर (Quantum Fusion Core)",
    titleEn: "Superconducting Quantum Fusion Core",
    categoryHi: "साइंस व तकनीक",
    categoryEn: "Sci-Fi Tech",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 91,
    titleHi: "दिव्य श्रीयंत्र मंडल (Sacred Sri Yantra)",
    titleEn: "Sacred Golden Sri Yantra Mandala",
    categoryHi: "धार्मिक व आध्यात्मिक कला",
    categoryEn: "Sacred Spiritual Art",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 92,
    titleHi: "स्वर्ण ड्रैगन की उड़ान (Golden Mythic Dragon)",
    titleEn: "Golden Celestial Dragon Flight",
    categoryHi: "पौराणिक गाथाएं",
    categoryEn: "Mythology & Fantasy",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 93,
    titleHi: "शाही राजस्थानी चित्रकला (Royal Miniature Art)",
    titleEn: "Indian Royal Heritage Miniature Painting",
    categoryHi: "भारतीय धरोहर कला",
    categoryEn: "Traditional Indian Art",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 94,
    titleHi: "दीपावली जगमगाती रंगोली (Diwali Diya Rangoli)",
    titleEn: "Diwali Golden Diya & Floral Rangoli",
    categoryHi: "भारतीय त्योहार",
    categoryEn: "Indian Festivals",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 95,
    titleHi: "नटराज तांडव दिव्य आभा (Cosmic Nataraja)",
    titleEn: "Nataraja Cosmic Dance of Creation",
    categoryHi: "धार्मिक व आध्यात्मिक कला",
    categoryEn: "Spiritual Arts",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 96,
    titleHi: "सूक्ष्म मयूर पंख चमक (Peacock Feather Macro)",
    titleEn: "Microscopic Iridescent Peacock Feather",
    categoryHi: "सूक्ष्म प्राकृतिक कला",
    categoryEn: "Macro Nature",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 97,
    titleHi: "डायमंड क्रिस्टल फ्रैक्टल (Diamond Fractal)",
    titleEn: "Diamond Crystallographic Fractals",
    categoryHi: "अमूर्त कला",
    categoryEn: "Abstract Fractals",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 98,
    titleHi: "फिनिक्स अमर अग्नि पक्षी (Phoenix Rebirth)",
    titleEn: "Mythical Fire Phoenix Rising",
    categoryHi: "पौराणिक गाथाएं",
    categoryEn: "Mythology & Fantasy",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 99,
    titleHi: "महाकाल ब्रह्मांडीय ऊर्जा (Cosmic Energy Storm)",
    titleEn: "Cosmic Vortex Quantum Energy Storm",
    categoryHi: "ब्रह्मांडीय शक्ति",
    categoryEn: "Cosmic Power",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "ग्रैंडमास्टर (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Grandmaster (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 100,
    titleHi: "परम चक्रव्यूह 100X (The Ultimate 100X Labyrinth)",
    titleEn: "The Ultimate 100X Supreme Labyrinth",
    categoryHi: "10X ग्रैंड फिनाले",
    categoryEn: "10X Grand Championship Finale",
    gridSize: 5,
    hasRotation: true,
    difficultyHi: "अल्टीमेट 100X चैंपियन (5x5 + उल्टे टुकड़े ↺)",
    difficultyEn: "Ultimate 100X Champion (5x5 + Rotated ↺)",
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
  }
];

// Fallback high quality patterned SVG in case an external image cannot load
export function createFallbackPatternSvg(title: string, color1: string = '#f59e0b', color2: string = '#b45309'): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600">
    <defs>
      <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="${color1}" />
        <stop offset="100%" stop-color="${color2}" />
      </linearGradient>
      <pattern id="pat" width="40" height="40" patternUnits="userSpaceOnUse">
        <circle cx="20" cy="20" r="10" fill="rgba(255,255,255,0.15)" />
        <path d="M 0 0 L 40 40 M 40 0 L 0 40" stroke="rgba(255,255,255,0.1)" stroke-width="2" />
      </pattern>
    </defs>
    <rect width="600" height="600" fill="url(#grad)" />
    <rect width="600" height="600" fill="url(#pat)" />
    <circle cx="300" cy="300" r="160" fill="rgba(255,255,255,0.2)" stroke="#fff" stroke-width="6" />
    <circle cx="300" cy="300" r="100" fill="none" stroke="rgba(255,255,255,0.4)" stroke-dasharray="8 8" stroke-width="4" />
    <text x="300" y="305" font-size="28" font-family="sans-serif" font-weight="bold" fill="#ffffff" text-anchor="middle" dominant-baseline="middle">${title}</text>
    <text x="300" y="345" font-size="18" font-family="sans-serif" fill="rgba(255,255,255,0.9)" text-anchor="middle">30s Puzzle Challenge</text>
  </svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}
